CREATE DATABASE ThuVienOnLine
GO
USE ThuVienOnLine
GO

CREATE TABLE NguoiDung
(
UserID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
FullName NVARCHAR(200) NOT NULL,
Ngaysinh Date NOT NULL,
GioiTinh Bit Not Null,
Anh NVARCHAR(Max),
Diachi NVARCHAR(500),
Phone NVARCHAR(20) NOT NULL,
Email NVARCHAR(200) NOT NULL,
Password varchar(26) NOT NULL
)
GO

CREATE TABLE TheLoai
(
TheLoaiID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TheLoaiName NVARCHAR(500) NOT NULL
)
GO

CREATE TABLE Book
(
BookID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
TheLoai INT FOREIGN KEY REFERENCES TheLoai(TheLoaiID),
TheLoaiID INT NOT NULL,
BookName NVARCHAR(500) NOT NULL,
TacGia NVARCHAR(200) NOT NULL,
Anh NVARCHAR(MAX) NOT NULL,
NgayPH DATE NOT NULL,
SoTrang INT Not Null,
Mota NVARCHAR(MAX) NOT NULL
)
GO

